version: '3.4'

services:
  mysql-transfer:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password

  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1

  broker:
    image: confluentinc/cp-kafka:6.1.1
    
  banking.operation.transfer.command.api:
    image: ${DOCKER_REGISTRY-}bankingoperationtransfercommandapi
    build:
      context: .
      dockerfile: Banking.Operation.Transfer.Command.Api/Dockerfile
      
networks:
  default:
    external: true
    name: bankingoperation-client-api_backend